[package]
name = "rust-15puzzle-cli"
version = "0.1.0"
authors = ["24seconds <24crazyoung@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
termion = "1.5.5"
tui="0.9.1"